OmnifactoryDevs/Omnifactory

overrides/config/betterquesting/DefaultQuests.json

> Everything looks a little bit crammed though. Visible layout also shows what quests depend on (not being able to do so sometimes hinders the progression so much), otherwise you're down to having to guess what you have to unlock first to enable progressing through the current quest chain you're doing.
Based on multiple opinions from players, it's best to make it visible by default.

Make the questbook layout visible by default

---

overrides/scripts/ContentTweaker.zs

Implement burn damage from Hot Draconium Ingots and reduce stack size to 16.
May need testing:
With the fix installed, die. This caused invulnerability for me until server restart. This may or may not have been caused by this change.

Hot Draconium Ingot Fix

---

overrides/scripts/ExtendedCrafting.zs

This changes the amount of Molten Creative Portable Tank a Heart produces from 288mb to 145mb, which prevents players from accidentally making two tanks by leaving exacty 1mb of fluid in the input, to configure the freshly crafted Creative Portable Tank with.
Should not break any current setups.

Change the amount of Molten Tank produced by a Heart

---

overrides/config/Building Gadgets.cfg

This is by no means a full list of blocks that can be used like that, but it will make it just a bit harder.

Blacklist certain blocks to prevent Exchanger Gadget mining

---

overrides/scripts/Earlygame.zs

Not used anywhere aside from duping phosphorus

🦀 Remove phosphorus pentoxide 🦀

---

overrides/scripts/Endgame.zs
overrides/scripts/Microverse.zs

This should close #175 . I tested it by hand crafting, where it worked with multiple wrenches, not just the Darmstadtium one. It also worked when the wrenches were damaged. I also tested the pattern with the wrench in AE, as it was mentioned that it would not work there, and the pattern worked fine (Make sure ore-dict substitutions is enabled for anyone who uses this pattern instead of the assembler). It should also fix a similar case with the LuV machine casing, where it was only craftable with the Darmstadtium wrench.

Should fix MM casings being craftable by hand

---

overrides/scripts/_oreDict.zs

Closes #200 
Simply adds the GTCE aluminum block to the chisel oredict for aluminum blocks. This results in having the GTCE block in both aluminum oredicts, but it should be fine.

Allow GTCE aluminum to be chiselable

---

manifest.json
overrides/scripts/EnderIO.zs
overrides/scripts/_oreDict.zs

Bumps EnderIO and related mods to the latest version and fixes several recipes, Blank Dark Steel Upgrade being one of them.

Update EnderIO and related mods

---

overrides/scripts/Earlygame.zs
overrides/scripts/SolarFlux.zs

Adds a dirt recipes, fixes #197 
Let me know if you want me to move the recipe to a different file, I just stuck in in the Earlygame script because dirt is an early game item. I also removed the non-functional dirt recipe, with the slag and the pulped biomass. I considered using a Plant Ball instead of the clay, but that gave the possibility for duping dirt via the centrifuge, which is not that big of a problem, but I figured I would avoid it anyway.

Add dirt recipe

---

overrides/scripts/EnderIO.zs
overrides/scripts/Midgame.zs

Closes #216 
The two enlightened variants simply combine the glass with a block of glowstone, and are available at LV since the original glass blocks are available then as well. The Dark glass variant combines black quartz with quite clear glass to make it a little bit harder, as it prevents light from going through. This variant requires either early exploration to find some black quartz ore, or waiting until MV to be able to make black quartz dust.

Add additional Enderio Glasses

---

manifest.json
modlist.html
overrides/config/loottweaker.cfg
overrides/scripts/LootTweaker.zs

Prevents pre-charged Zero Point Modules from generating in jungle temples.
These things are OP and since the pack allows putting them in LV-LuV CEFs/CEUs they eliminate the need of setting up (at least early) power generation, a player can easily just loot himself a virtually infinite power source.
Adds LootTweaker 0.1.5 as dependency.

Remove ZPMs from the jungle temple loot table

---

overrides/scripts/Earlygame.zs
overrides/scripts/Electronics.zs
overrides/scripts/JetpacksAndEnergyStorage.zs
overrides/scripts/_oreDict.zs

Fixes Micro Miner Engine Cores/Frames being invisible in JEI.
Also removes the Thermal Expansion variant of Sawdust:
> Something I noticed while unhiding Micro Miner Engines.
Currently the TE Sawdust variant is 1:1 identical to the GTCE variant, and adds nothing but unnecessary clutter to JEI.
> Adds a recipe to convert the obsolete variant to the useful one.
Thanks to [Coffee](https://steamcommunity.com/id/nntoxic/) for reporting it.

Unhide Micro Miner Cores/Frames and remove TE Sawdust

---

overrides/scripts/Electronics.zs

I tried just replacing gregtech:meta_tool:8 with ore:craftingToolWrench, but that made it uncraftable with regular wrenches, aside from undamanged darmstatium one.
As a workaround, I added a second recipe which has ore:craftingToolWrench, making them craftable with electric wrenches.
I also noticed that the MAX casings made from moar plates have the same issue so I fixed it as well.

Fixed ULV, LV and MAX casings not craftable with electric wrenches

---

overrides/scripts/EnderIO.zs

Adds additional recipes for Z-Logic Controllers, Ender Resonators, Skeletal Contractors and Guardian Diodes taking Glowstone-Doped and Naquadah wafers and providing better yield. Removes the post-tank dependency on regular wafers. Helps with the zombie head grind.
1x with regular wafers, 2x with Glowstone-Doped, 4x with Naquadah.
Might be worth it buffing up to 1/4/8.
Closes #177.

Add extra S'n'S recipes taking better wafers

---

overrides/config/AE2WirelessTerminals.cfg
overrides/scripts/AE2.zs

Closes #328 
Adjusts the config of wireless AE to make the Infinity Booster Card last forever, and also removes it as a drop from endermen and the wither.
Also as Neeve mentioned in the issue, adjusts the recipe of the booster card, to make it slightly more difficult. Right now, I just replaced the two singularities with IV tier circuits. Let me know if there is a more suitable material.

Make booster card infinite, adjust recipe

---

overrides/scripts/Armors.zs

This is in line with the other Ultimate Armours, and they are still required to craft the Infinity Boots, again in line with the other Infinity Armours.
Replaces both with more Ultimate Gems.

Change Ultimate boots recipe to not use Wyvern and Draconic boots.

---

overrides/scripts/Earlygame.zs
overrides/scripts/Endgame.zs
overrides/scripts/OreProcessing/DenseOres.zs
overrides/scripts/OreProcessing/ExquisiteGems.zs

Both code sections are related to ore processing and don't belong to Endgame.zs at all.
This PR also:
* adds ore dictionary entries for Dense Ores (denseOre*);
* hides exquisite, flawless, flawed and chipped versions of lapis and coal coke;
* fixes ratios of exquisite gems to gem dusts;
* prettifies both scripts to remove duplicate code and increase readability.

Split Dense Ores and Exquisite Gems into separate files

---

overrides/scripts/Alchemy.zs
overrides/scripts/Earlygame.zs
overrides/scripts/ExtendedCrafting.zs
overrides/scripts/_oreDict.zs

Makes the CraftTweaker variant uncraftable but usable in recipes and adds a tooltip to it.
Adds a shapeless conversion recipe.
Removes the NuclearCraft variant from `<ore:dustEndstone>`.
Closes #365.

Make GT Endstone Dust the default variant

---

overrides/config/gtadditions.cfg
overrides/scripts/JEICleanup.zs

These items are unused in Omnifactory, and can be removed in configs to reduce load times and JEI clutter.

Disable double ingots and curved plates

---

overrides/scripts/ExtendedCrafting.zs

Closes #259 
See my comment in that issue about why this happens. As a result of fixing this error, I removed the added implosion compressor recipe that took gtce explosives leaving the tnt recipe, as I was unsure if we wanted this still gated behind tnt only.

Fix Validation error in #259

---

overrides/config/scannable.cfg

Add unique colors to every overworld deposit, to make them stand out at a glance. Also add more copper, tin, and iron ores to "common"-type scannables, remove aluminium and cinnabar from common-type.

Add unique colors to every ore deposite in Scannable

---

overrides/scripts/BlastFurnace.zs
overrides/scripts/Earlygame.zs
overrides/scripts/ExtendedCrafting.zs
overrides/scripts/JEICleanup.zs
overrides/scripts/Nuclearcraft.zs
overrides/scripts/ThermalExpansion.zs
overrides/scripts/_oreDict.zs

Fixes #404 but also scope crept into an overhaul of cleanup for NuclearCraft.
Removing dead-end paths in crafting, clearing out unusable machinery/items/recipes from the registry and JEI, and reorganizing some of the script file structure to better handle the same.

NC Cleanup Effort

---

overrides/scripts/Microverse.zs

5x power usage, 0.8x recipe length, 4x output and inputs. As such, efficiency is unchanged.
Note: this means the rig now requires a hatch capable of 17.5KRF/t.
Fixes #347.

Oil Rig Rebalance
